### ISSUE TITLE
Multiple decorators are not getting called

### ISSUE THREAD

**Issue by jveres** [denofn/denopack#36]
Multiple decorators are not getting called.

Reproduce the behavior with test.ts:

```typescript
function A() {
  console.log("@A evaluated");
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor,
  ) {
    console.log("@A called");
    const fn = descriptor.value;
    descriptor.value = function() {
      console.log("fn() called from @A");
      fn();  
    };
  };
}

function B() {
  console.log("@B evaluated");
  return function (
    target: any,
    propertyKey: string,
    descriptor: PropertyDescriptor,
  ) {
    console.log("@B called");
    const fn = descriptor.value;
    descriptor.value = function() {
      console.log("fn() called from @B");
      fn();  
    };
  };
}

class C {
  @A()
  @B()
  static test() {
    console.log("C.test() called");
  }
}

C.test();
```
```sh
denopack -i test.ts
denopack completed in 405ms
deno run bundle.js   
@A evaluated
@B evaluated
@B called
@B called
fn() called from @B
fn() called from @B
C.test() called
```

**Expected behavior**
```sh
@A evaluated
@B evaluated
@B called
@A called
fn() called from @A
fn() called from @B
C.test() called
```

- OS: macOS
- Deno version 1.5.2
- denopack version 0.10.0

**Comment by jveres** [comment]
Further investigating this issue I found, that using the `test.ts` above `Deno.transpileOnly(...)` is responsible to give the following and obviously faulty result:
```javascript
function _applyDecoratedDescriptor(target, property, decorators, descriptor, context) {
    var desc = {
    };
    Object.keys(descriptor).forEach(function(key) {
        desc[key] = descriptor[key];
    });
    desc.enumerable = !!desc.enumerable;
    desc.configurable = !!desc.configurable;
    if ("value" in desc || desc.initializer) {
        desc.writable = true;
    }
    desc = decorators.slice().reverse().reduce(function(desc, decorator) {
        return decorator(target, property, desc) || desc;
    }, desc);
    if (context && desc.initializer !== void 0) {
        desc.value = desc.initializer ? desc.initializer.call(context) : void 0;
        desc.initializer = undefined;
    }
    if (desc.initializer === void 0) {
        Object.defineProperty(target, property, desc);
        desc = null;
    }
    return desc;
}
var _class, _dec, _dec;
function A() {
    console.log("@A evaluated");
    return function(target, propertyKey, descriptor) {
        console.log("@A called");
        const fn = descriptor.value;
        descriptor.value = function() {
            console.log("fn() called from @A");
            fn();
        };
    };
}
function B() {
    console.log("@B evaluated");
    return function(target, propertyKey, descriptor) {
        console.log("@B called");
        const fn = descriptor.value;
        descriptor.value = function() {
            console.log("fn() called from @B");
            fn();
        };
    };
}
let C = ((_class = class C {
    static test() {
        console.log("C.test() called");
    }
}) || _class, _dec = A(), _dec = B(), _applyDecoratedDescriptor(_class, "test", [_dec, _dec], Object.getOwnPropertyDescriptor(_class, "test"), _class), _class);
C.test();
```
However, `Deno.compile(...)` emits properly working code:
```javascript
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
function A() {
    console.log("@A evaluated");
    return function (target, propertyKey, descriptor) {
        console.log("@A called");
        const fn = descriptor.value;
        descriptor.value = function () {
            console.log("fn() called from @A");
            fn();
        };
    };
}
function B() {
    console.log("@B evaluated");
    return function (target, propertyKey, descriptor) {
        console.log("@B called");
        const fn = descriptor.value;
        descriptor.value = function () {
            console.log("fn() called from @B");
            fn();
        };
    };
}
class C {
    static test() {
        console.log("C.test() called");
    }
}
__decorate([
    A(),
    B()
], C, "test", null);
C.test();
```
The default in `denopack` is to use `Deno.transpileOnly`.
Using `pluginTypescriptCompile` gives error:
```sh
error: Uncaught (in promise) TypeError: Cannot read property 'includes' of undefined
  if (!files.includes(jsFile)) {
             ^
    at resolveFromModules (mod.ts:21:14)
    at Object.transform (mod.ts:72:35)
    at https://unpkg.com/rollup@2.26.11/dist/es/rollup.browser.js:11:334078
```

**Comment by jveres** [comment]
Related Deno issue https://github.com/denoland/deno/issues/8412
