### ISSUE TITLE
[BUG] Getting a 500 Internal Server Error while installing

### ISSUE THREAD

**Issue by ohmlnz** [denofn/denopack#39]
**Describe the bug**

I'm getting a `500 Internal Server Error` when running: 

```bash
deno run --allow-run --allow-read https://x.nest.land/denopack@0.10.0/install.ts
```

**Screenshots**

```bash
Download https://cdn.dreg.dev/polyfill/node/path.ts
Download https://cdn.dreg.dev/package/@types/estree@0.0.45
error: Import 'https://cdn.dreg.dev/package/picomatch@2.2.2' failed: 500 Internal Server Error
    at https://cdn.dreg.dev/package/@rollup/pluginutils@4.0.0/dist/es/index.js:2:0
error: Uncaught (in promise) AssertionError: Failed to install plugin dependencies.
    throw new AssertionError(msg);
          ^
    at assert (asserts.ts:156:11)
    at install.ts:63:1
```

**Desktop (please complete the following information):**

- OS: macOS Catalina
- Deno version: 1.5.4
- denopack version: 0.10.0

**Additional context**

The issue appears to be at the CDN level given that this is not reachable: [https://cdn.dreg.dev/package/picomatch@2.2.2](https://cdn.dreg.dev/package/picomatch@2.2.2). Not sure if I should have opened this issue on the [Dreg](https://github.com/denofn/dreg) repo instead. 

**Checklist**

- [x] I am using Deno version 1.2.0 or higher

**Comment by ohmlnz** [comment]
Looks like the issue got resolved. Closing the PR.
