### ISSUE TITLE
[BUG] Debugging experience is very poor

### ISSUE THREAD

**Issue by resynth1943** [denofn/denopack#44]
**Describe the bug**

When Rollup encounters a runtime error, it leaves you with very little to go on -- aside from a stack trace, containing mangled function names and hard-to-reach line numbers.

This doesn't really help:

```
[resynth@synthcave synth-di]$ time deno run --unstable --allow-read --allow-write --allow-env --allow-net https://deno.land/x/denopack@0.10.0/cli.ts --config ./build/base.config.ts
error: Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at Ve (https://unpkg.com/rollup@2.26.11/dist/es/rollup.browser.js:11:31514)
    at Ra (https://unpkg.com/rollup@2.26.11/dist/es/rollup.browser.js:11:318386)
    at async Ua.loadEntryModule (https://unpkg.com/rollup@2.26.11/dist/es/rollup.browser.js:11:327081)
    at async Promise.all (index 0)
```

**To Reproduce**

1. Encounter a runtime error in Rollup

**Expected behavior**

You get an un-minifed error.
The Rollup module you're importing does not come with a source map, btw.

**Comment by resynth1943** [comment]
I see two ways to fix this:

- stop including the minified version of Rollup, and use the clear one instead
- encourage Rollup developers to include a source-map in the bundle (I'm not sure if Deno supports source maps?)

**Comment by probins** [comment]
this is surely an issue for Rollup - it ought to be simple for them to add a sourcemap to the browser output file (I'm not sure how much the browser file is actually used).

Deno [supports](https://deno.land/manual@v1.6.2/getting_started/debugging_your_code) V8 Inspector (I often use the `inspect-brk` option), though I think you have to use `deno run` - I don't think it works as an option on the installed `denopack`.

**Comment by resynth1943** [comment]
It may be a Rollup issue, yes. Good point.

**Comment by cmorten** [comment]
FYI I have raised an issue for the particular error you reference above https://github.com/rollup/rollup/issues/3934 and a PR to fix https://github.com/rollup/rollup/pull/3935 in the Rollup project. Doesn’t help with the debugging aspect of this issue, but may provide some more context what the error is, why it occurs and hopefully a path forward towards fixing it.
